---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Unesco sites app"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /nearby:
    get:
      description: "Returns 'nearby' to the caller"
      operationId: "nearby"
      parameters:
      - name: "lat"
        in: "query"
        description: "Latitude of selected location"
        required: true
        type: "number"
      - name: "lng"
        in: "query"
        description: "longitude of selected location"
        required: true
        type: "number"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/NearbyResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "nearby_search"
  /swagger:
    x-swagger-pipe: "swagger_raw"
definitions:
  NearbyResponse:
    required:
    - "nearby_sites"
    properties:
      nearby_sites:
        type: "array"
        items:
          $ref: "#/definitions/SiteObject"
    example:
      nearby_sites:
      - site_name: "site_name"
        agent_name: "agent_name"
      - site_name: "site_name"
        agent_name: "agent_name"
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
  SiteObject:
    required:
    - "site_name"
    properties:
      site_name:
        type: "string"
      agent_name:
        type: "string"
    example:
      site_name: "site_name"
      agent_name: "agent_name"
